// <auto-generated />
namespace ClimaTempo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Migracaoinicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migracaoinicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202204211902150_Migracao inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
